### ISSUE TITLE
Create NTP module

### ISSUE THREAD

**Issue by Themimitoof** [Enowaves/Magellan#13]
The NTP module are our "test" module. Is created for testing and optimizing the architecture of the project before creating new modules.

Basically, the user can add client restrictions (_restrict command_) and add upstream servers (_server command_). For "unique" configuration commands (_logs, fudge, stats, listen, ..._), we are searching the best way to store the configuration (_if you have ideas, please expose them_).

**Note :** the creation of the model are based on the configuration file of _ntpd server_.

## Tasks
- [ ] Create _restrictions_ model
- [ ] Create _servers_ model
- [ ] Create REST endpoints (_GET, POST, PUT, DELETE_)
  - [ ] Create filter system based on the column name for _GET_ requests_

**Note 2:** don't think about the authentication and the permissions management, he will be managed by the authentication module (created soon)
