### ISSUE TITLE
Setup Celery

### ISSUE THREAD

**Issue by Themimitoof** [Enowaves/Magellan#4]
Make some tests with Celery and setup them with Redis instead of RabbitMQ.

## Tasks
- [ ] Setup Celery on the project
- [ ] Create NTP orchestrator tasks (not the *reload_configuration*)
- [ ] Make tasks routage (tasks starting with _start, reload, restart_ are assigned to _orchestrator_ queue, the rest are assigned to the _module name_ queue)
